### ISSUE TITLE
[1.12.2] Crash on server startup

### ISSUE THREAD

**Issue by Gbergz** [UpcraftLP/CraftDev-Core#8]
Server is crashing when starting up.
Im on the latest version released and on mc v1.12.2

crashlog:
[Pastebin](https://pastebin.com/0cy4Zk71)

**Comment by UpcraftLP** [comment]
strange, seems like the server has different libraries than the client....
anyway, that class was meant for a client only feature so I just removed that call from the server.

**Comment by UpcraftLP** [comment]
fixed in release [v2.2.8](https://github.com/UpcraftLP/CraftDev-Core/releases/tag/v2.2.8) ([CurseForge](https://minecraft.curseforge.com/projects/craftdev-core/files/2488996))
